#!/usr/bin/env bash
# PreCompact hook: Capture current git state before context compaction.
# Writes to .claude/wip-context.md so SessionStart can re-inject it.
# Produces no stdout (informational only, exit 0).

set -euo pipefail

WIP_FILE=".claude/wip-context.md"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Get git state (gracefully handle missing git)
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
RECENT_COMMITS=$(git log --oneline -5 2>/dev/null || echo "  (no commits)")
UNCOMMITTED=$(git diff --stat 2>/dev/null || echo "  (no changes)")
STATUS=$(git status --short 2>/dev/null || echo "  (unknown)")

cat > "$WIP_FILE" << EOF
## WIP Context (auto-generated by PreCompact hook)
- **Branch:** ${BRANCH}
- **Timestamp:** ${TIMESTAMP}

### Recent Commits
\`\`\`
${RECENT_COMMITS}
\`\`\`

### Uncommitted Changes
\`\`\`
${UNCOMMITTED}
\`\`\`

### Working Tree Status
\`\`\`
${STATUS}
\`\`\`
EOF

exit 0
