# PreCompact hook: Capture current git state before context compaction.
# Writes to .claude/wip-context.md so SessionStart can re-inject it.
# Produces no stdout (informational only, exit 0).

$ErrorActionPreference = "Stop"

$wipFile = ".claude/wip-context.md"
$timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

# Get git state (gracefully handle missing git)
try {
    $branch = git branch --show-current 2>$null
    if (-not $branch) { $branch = "unknown" }
} catch {
    $branch = "unknown"
}

try {
    $recentCommits = git log --oneline -5 2>$null
    if (-not $recentCommits) { $recentCommits = "  (no commits)" }
} catch {
    $recentCommits = "  (no commits)"
}

try {
    $uncommitted = git diff --stat 2>$null
    if (-not $uncommitted) { $uncommitted = "  (no changes)" }
} catch {
    $uncommitted = "  (no changes)"
}

try {
    $status = git status --short 2>$null
    if (-not $status) { $status = "  (unknown)" }
} catch {
    $status = "  (unknown)"
}

# Write WIP context file
@"
## WIP Context (auto-generated by PreCompact hook)
- **Branch:** $branch
- **Timestamp:** $timestamp

### Recent Commits
``````
$recentCommits
``````

### Uncommitted Changes
``````
$uncommitted
``````

### Working Tree Status
``````
$status
``````
"@ | Out-File -FilePath $wipFile -Encoding UTF8

exit 0
